In [1]:
import os, datetime
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

from tensorflow import keras
from utils.dataset import load_dataset_v2,create_lstm_dataset
from utils.metric import smape
from utils.assemble_model import build_model_v1
from matplotlib.ticker import MultipleLocator
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score, mean_absolute_percentage_error


print("TensorFlow version:", tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("Available GPUs:", tf.config.list_physical_devices('GPU'))

2025-10-18 02:32:44.492928: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-18 02:32:44.505267: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1760722364.522142 1523124 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1760722364.527088 1523124 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1760722364.538258 1523124 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1760722364.538276 1523124 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1760722364.538278 1523124 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1760722364.538279 1523124 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-10-18 02:32:44.542900: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')

I0000 00:00:1760722366.456825 1523124 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46412 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:4b:00.0, compute capability: 8.6
I0000 00:00:1760722366.458360 1523124 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 46718 MB memory:  -> device: 1, name: NVIDIA RTX A6000, pci bus id: 0000:b1:00.0, compute capability: 8.6

number of available gpus: 2
TensorFlow version: 2.19.1
Num GPUs Available: 2
Available GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [2]:
feature_name_list = ['pressure_1(bar)', 'main_pressure(bar)']
target_name = 'outlet_flowrate(lpm)'

file_name_list = os.listdir(os.path.join('data', 'ver_2'))
file_path_list = []

for file_name in file_name_list:
    file_path_list.append(os.path.join('data', 'ver_2', file_name))

dataset = load_dataset_v2(file_path_list)
dataset = dataset[::10]
dataset.reset_index(drop=True, inplace=True)

dataset.shape

loading dataset...:   0%|          | 0/84 [00:00<?, ?it/s]

(231525, 18)

In [3]:
new_dataset = dataset.copy()
new_dataset = new_dataset[new_dataset[target_name] > 1]

train_bool_list = new_dataset['test_case_iter']!=3
train_data = new_dataset[train_bool_list]
train_data.reset_index(drop=True, inplace=True)

val_bool_list = new_dataset['test_case_iter']==3
val_data = new_dataset[val_bool_list]
val_data.reset_index(drop=True, inplace=True)

print(train_data.shape)
print(val_data.shape)

(132546, 18)
(64001, 18)

In [4]:
train_data

,time(s),pressure_1(bar),main_pressure(bar),venturi_pressure_1(bar),venturi_pressure_2(bar),venturi_pressure_3(bar),venturi_pressure_4(bar),venturi_pressure_5(bar),pump_speed(rpm),water_temp(c),reserved,outlet_flowrate(lpm),inlet_flowrate(lpm),test_case,test_case_iter,nozzle_len(mm),nozzle_dia(mm),venturi_dist(mm)
0,26.4,-0.16,1.09,1.05,0.05,0.08,0.14,0.12,891.59,32.18,0.0,1.01,-2.18,43.0,2.0,36.0,20.0,30.0
1,26.6,-0.11,1.23,1.10,0.04,0.06,0.07,0.10,899.47,32.22,0.0,1.07,-2.63,43.0,2.0,36.0,20.0,30.0
2,35.6,-0.13,1.12,1.10,0.10,0.07,0.18,0.12,896.88,32.26,0.0,1.20,-2.09,43.0,2.0,36.0,20.0,30.0
3,36.8,-0.15,1.06,1.12,0.09,0.08,0.14,0.10,896.72,32.26,0.0,1.56,-2.26,43.0,2.0,36.0,20.0,30.0
4,42.9,-0.11,1.10,1.11,0.06,0.06,0.11,0.08,902.44,32.25,0.0,2.77,-2.03,43.0,2.0,36.0,20.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132541,365.8,-0.04,-0.09,0.01,0.03,0.06,0.06,0.05,-0.05,32.38,0.0,22.72,-2.00,21.0,1.0,24.0,15.8,0.0
132542,365.9,-0.05,-0.07,0.04,0.09,0.09,0.08,0.03,-0.06,32.37,0.0,15.06,-2.36,21.0,1.0,24.0,15.8,0.0
132543,366.0,-0.03,-0.01,0.04,0.07,0.05,0.04,0.02,-0.06,32.37,0.0,7.55,-2.68,21.0,1.0,24.0,15.8,0.0
132544,366.1,-0.03,-0.09,0.01,0.03,0.06,0.07,0.08,-0.07,32.38,0.0,6.79,-2.59,21.0,1.0,24.0,15.8,0.0
132545,366.2,-0.06,-0.07,0.02,0.09,0.08,0.07,0.03,-0.06,32.38,0.0,6.85,-2.22,21.0,1.0,24.0,15.8,0.0

In [5]:
val_data

,time(s),pressure_1(bar),main_pressure(bar),venturi_pressure_1(bar),venturi_pressure_2(bar),venturi_pressure_3(bar),venturi_pressure_4(bar),venturi_pressure_5(bar),pump_speed(rpm),water_temp(c),reserved,outlet_flowrate(lpm),inlet_flowrate(lpm),test_case,test_case_iter,nozzle_len(mm),nozzle_dia(mm),venturi_dist(mm)
0,28.0,-0.13,2.57,2.62,0.06,0.05,0.03,0.09,894.70,30.44,0.0,1.09,-2.40,40.0,3.0,36.0,15.8,60.0
1,30.1,-0.13,2.63,2.62,0.06,0.06,0.03,0.09,906.33,30.43,0.0,1.09,-2.78,40.0,3.0,36.0,15.8,60.0
2,32.5,-0.03,2.54,2.62,0.07,0.09,0.04,0.10,921.39,30.35,0.0,16.10,-2.46,40.0,3.0,36.0,15.8,60.0
3,32.6,-0.09,2.55,2.57,0.01,0.03,0.04,0.13,908.07,30.32,0.0,32.95,-2.39,40.0,3.0,36.0,15.8,60.0
4,32.7,-0.08,2.46,2.58,0.03,0.10,0.14,0.14,897.98,30.35,0.0,51.28,-2.75,40.0,3.0,36.0,15.8,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63996,236.5,-0.04,-0.11,0.03,0.09,0.11,0.09,0.03,-0.02,28.99,0.0,45.19,-2.26,18.0,3.0,24.0,12.0,30.0
63997,236.6,-0.01,-0.01,0.06,0.08,0.07,0.00,-0.00,-0.04,28.99,0.0,29.59,-2.24,18.0,3.0,24.0,12.0,30.0
63998,236.7,-0.02,-0.12,0.01,0.05,0.06,0.07,0.05,-0.08,29.00,0.0,13.85,-2.56,18.0,3.0,24.0,12.0,30.0
63999,236.8,-0.04,-0.10,0.03,0.10,0.12,0.07,0.04,-0.05,29.00,0.0,13.29,-2.78,18.0,3.0,24.0,12.0,30.0
64000,236.9,-0.01,-0.03,0.06,0.07,0.07,0.02,-0.01,-0.07,29.00,0.0,13.48,-2.46,18.0,3.0,24.0,12.0,30.0

In [6]:
train_feature = train_data[feature_name_list].to_numpy()
val_feature = val_data[feature_name_list].to_numpy()

train_target = train_data[target_name].to_numpy()
val_target = val_data[target_name].to_numpy()

train_target = train_target.reshape(-1, 1)
val_target = val_target.reshape(-1, 1)

scaler = StandardScaler()
scaler.fit(train_target)

train_target = scaler.transform(train_target)
val_target = scaler.transform(val_target)

train_target = np.squeeze(train_target)
val_target = np.squeeze(val_target)

print(train_feature.shape, train_target.shape)
print(val_feature.shape, val_target.shape)

print((train_feature.itemsize*train_feature.size)/(1024**2))
print((train_target.itemsize*train_target.size)/(1024**2))

(132546, 2) (132546,)
(64001, 2) (64001,)
2.022491455078125
1.0112457275390625

In [7]:
print(np.min(train_target), np.max(train_target))
print(np.min(val_target), np.max(val_target))

-2.088246215114446 2.246874528833561
-2.088246215114446 2.310018313330957

In [8]:
n_samples = 1000
max_len = 1000

random_start_idx = np.random.randint(low=0, high=train_feature.shape[0]-max_len, size=n_samples)
random_len_idx = np.random.randint(low=300, high=max_len+1, size=n_samples)

feature_buf = np.empty(shape=(0, 2))
target_buf = np.empty(shape=(0,))

for i, j in zip(random_start_idx, random_len_idx):
    feature_buf = np.concatenate([feature_buf, train_feature[i:i+j]], axis=0)
    target_buf = np.concatenate([target_buf, train_target[i:i+j]], axis=0)

new_train_feature = feature_buf
new_train_target = target_buf


random_start_idx = np.random.randint(low=0, high=train_feature.shape[0]-max_len, size=n_samples)
random_len_idx = np.random.randint(low=300, high=max_len+1, size=n_samples)

feature_buf = np.empty(shape=(0, 2))
target_buf = np.empty(shape=(0,))

for i, j in zip(random_start_idx, random_len_idx):
    feature_buf = np.concatenate([feature_buf, train_feature[i:i+j]*0.9], axis=0)
    target_buf = np.concatenate([target_buf, train_target[i:i+j]*0.9], axis=0)

new_train_feature = np.concatenate([new_train_feature, feature_buf], axis=0)
new_train_target = np.concatenate([new_train_target, target_buf], axis=0)


random_start_idx = np.random.randint(low=0, high=train_feature.shape[0]-max_len, size=n_samples)
random_len_idx = np.random.randint(low=300, high=max_len+1, size=n_samples)

feature_buf = np.empty(shape=(0, 2))
target_buf = np.empty(shape=(0,))

for i, j in zip(random_start_idx, random_len_idx):
    feature_buf = np.concatenate([feature_buf, train_feature[i:i+j]*1.1], axis=0)
    target_buf = np.concatenate([target_buf, train_target[i:i+j]*1.1], axis=0)

new_train_feature = np.concatenate([new_train_feature, feature_buf], axis=0)
new_train_target = np.concatenate([new_train_target, target_buf], axis=0)

print(new_train_feature.shape, new_train_target.shape)

print((new_train_feature.itemsize*new_train_feature.size)/(1024**2))
print((new_train_target.itemsize*new_train_target.size)/(1024**2))

(1951822, 2) (1951822,)
29.782440185546875
14.891220092773438

In [9]:
seq_len = 30

train_feature, train_target = create_lstm_dataset(np.concatenate([new_train_feature, new_train_target.reshape(-1, 1)], axis=1), seq_len=seq_len,
                                                  pred_distance=0, target_idx_pos=train_feature.shape[1])
val_feature, val_target = create_lstm_dataset(np.concatenate([val_feature, val_target.reshape(-1, 1)], axis=1), seq_len=seq_len,
                                              pred_distance=0, target_idx_pos=val_feature.shape[1])

train_target = np.squeeze(train_target)
val_target = np.squeeze(val_target)

print(train_feature.shape, train_target.shape)
print(val_feature.shape, val_target.shape)

print((train_feature.itemsize*train_feature.size)/(1024**2))
print((train_target.itemsize*train_target.size)/(1024**2))

creating LSTM dataset...:   0%|          | 0/1951822 [00:00<?, ?it/s]

creating LSTM dataset...:   0%|          | 0/64001 [00:00<?, ?it/s]

(1951793, 30, 2) (1951793,)
(63972, 30, 2) (63972,)
893.4599304199219
14.890998840332031

In [10]:
model = build_model_v1(input_shape=(train_feature.shape[1:3]), d_dims=128, dropout_rate=0.5, learning_rate=0.001)

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 30, 2)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 30, 2)     │          8 │ input_layer[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 30, 128)   │        384 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ dense[0][0]       │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d (Conv1D)     │ (None, 30, 128)   │     49,280 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ conv1d[0][0]      │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 30, 128)   │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_1 (Conv1D)   │ (None, 30, 128)   │     49,280 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 30, 128)   │          0 │ conv1d_1[0][0],   │
│                     │                   │            │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalization │ (None, 30, 128)   │        256 │ add[0][0]         │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 30, 128)   │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 30, 128)   │          0 │ dropout_1[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ activation[0][0]  │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_2 (Conv1D)   │ (None, 30, 128)   │     49,280 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ conv1d_2[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 30, 128)   │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_3 (Conv1D)   │ (None, 30, 128)   │     49,280 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 30, 128)   │          0 │ conv1d_3[0][0],   │
│                     │                   │            │ activation[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 128)   │        256 │ add_1[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 30, 128)   │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 30, 128)   │          0 │ dropout_3[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ activation_1[0][… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_4 (Conv1D)   │ (None, 30, 128)   │     49,280 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ conv1d_4[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_4 (Dropout) │ (None, 30, 128)   │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_5 (Conv1D)   │ (None, 30, 128)   │     49,280 │ dropout_4[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_2 (Add)         │ (None, 30, 128)   │          0 │ conv1d_5[0][0],   │
│                     │                   │            │ activation_1[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 128)   │        256 │ add_2[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_5 (Dropout) │ (None, 30, 128)   │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_2        │ (None, 30, 128)   │          0 │ dropout_5[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ activation_2[0][… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_6 (Conv1D)   │ (None, 30, 128)   │     49,280 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ conv1d_6[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_6 (Dropout) │ (None, 30, 128)   │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_7 (Conv1D)   │ (None, 30, 128)   │     49,280 │ dropout_6[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_3 (Add)         │ (None, 30, 128)   │          0 │ conv1d_7[0][0],   │
│                     │                   │            │ activation_2[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 128)   │        256 │ add_3[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_7 (Dropout) │ (None, 30, 128)   │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_3        │ (None, 30, 128)   │          0 │ dropout_7[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ activation_3[0][… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_8 (Conv1D)   │ (None, 30, 128)   │     49,280 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ conv1d_8[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_8 (Dropout) │ (None, 30, 128)   │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_9 (Conv1D)   │ (None, 30, 128)   │     49,280 │ dropout_8[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_4 (Add)         │ (None, 30, 128)   │          0 │ conv1d_9[0][0],   │
│                     │                   │            │ activation_3[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 128)   │        256 │ add_4[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_9 (Dropout) │ (None, 30, 128)   │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_4        │ (None, 30, 128)   │          0 │ dropout_9[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 128)   │        256 │ activation_4[0][… │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 30, 16)    │      2,064 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm (LSTM)         │ (None, 30, 16)    │      2,112 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_5 (Add)         │ (None, 30, 16)    │          0 │ lstm[0][0],       │
│                     │                   │            │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 16)    │         32 │ add_5[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_1 (LSTM)       │ (None, 30, 16)    │      2,112 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_6 (Add)         │ (None, 30, 16)    │          0 │ lstm_1[0][0],     │
│                     │                   │            │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 16)    │         32 │ add_6[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_2 (LSTM)       │ (None, 30, 16)    │      2,112 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_7 (Add)         │ (None, 30, 16)    │          0 │ lstm_2[0][0],     │
│                     │                   │            │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 30, 16)    │         32 │ add_7[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expand_dims         │ (None, 1, 30, 16) │          0 │ layer_normalizat… │
│ (ExpandDims)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 32, 28,    │        320 │ expand_dims[0][0] │
│                     │ 14)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 28,    │        128 │ conv2d[0][0]      │
│ (BatchNormalizatio… │ 14)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_10          │ (None, 32, 28,    │          0 │ batch_normalizat… │
│ (Dropout)           │ 14)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 64, 26,    │     18,496 │ dropout_10[0][0]  │
│                     │ 12)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 64, 26,    │        128 │ conv2d_1[0][0]    │
│ (LayerNormalizatio… │ 12)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 64, 26,    │          0 │ layer_normalizat… │
│ (Dropout)           │ 12)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_5        │ (None, 64, 26,    │          0 │ dropout_11[0][0]  │
│ (Activation)        │ 12)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d       │ (None, 64, 13, 6) │          0 │ activation_5[0][… │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_1     │ (None, 64, 6, 3)  │          0 │ max_pooling2d[0]… │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_2     │ (None, 64, 3, 1)  │          0 │ max_pooling2d_1[… │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 192)       │          0 │ max_pooling2d_2[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 192)       │        384 │ flatten[0][0]     │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 1024)      │    197,632 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_12          │ (None, 1024)      │          0 │ dense_2[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 1)         │      1,025 │ dropout_12[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 726,457 (2.77 MB)

 Trainable params: 723,829 (2.76 MB)

 Non-trainable params: 2,628 (10.27 KB)

In [ ]:
log_dir = "logs/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)
early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=500, verbose=0)
csv_logger = keras.callbacks.CSVLogger('result/log.csv', append=False, separator=',')
model_chk_point = keras.callbacks.ModelCheckpoint(filepath='models/model.keras', monitor="val_loss", verbose=2, save_best_only=True,
                                                  save_weights_only=False, mode="min", save_freq="epoch", initial_value_threshold=None)

model.fit(x=train_feature, y=train_target, validation_data=(val_feature, val_target), epochs=999999,
          batch_size=10000, verbose=0, callbacks=[early_stop, csv_logger, model_chk_point, tensorboard_callback])

I0000 00:00:1760722397.214643 1523548 cuda_dnn.cc:529] Loaded cuDNN version 90101

Epoch 1: val_loss improved from None to 0.28926, saving model to models/model.keras

Epoch 2: val_loss improved from 0.28926 to 0.19965, saving model to models/model.keras

Epoch 3: val_loss improved from 0.19965 to 0.11668, saving model to models/model.keras

Epoch 4: val_loss improved from 0.11668 to 0.07491, saving model to models/model.keras

Epoch 5: val_loss improved from 0.07491 to 0.06126, saving model to models/model.keras

Epoch 6: val_loss improved from 0.06126 to 0.04954, saving model to models/model.keras

In [ ]:
#keras.utils.plot_model(model, show_shapes=True, show_layer_names=True, show_layer_activations=True, show_dtype=True)

In [ ]:
train_result = pd.read_csv('result/log.csv')

loss_df = train_result['loss']
val_loss_df = train_result['val_loss']
mean_abs_loss_df = train_result['mean_absolute_error']
val_mean_abs_loss_df = train_result['val_mean_absolute_error']
mean_abs_per_loss_df = train_result['mean_absolute_percentage_error']
val_mean_abs_per_loss_df = train_result['val_mean_absolute_percentage_error']

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

sns.lineplot(x=np.arange(0, len(loss_df)), y=loss_df, label='Train Loss', color='red')
sns.lineplot(x=np.arange(0, len(val_loss_df)), y=val_loss_df, label='Validation Loss', color='green')

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.yscale('log')

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

ax1 = sns.lineplot(x=np.arange(0, len(mean_abs_loss_df)), y=mean_abs_loss_df, label='Train Loss', color='red')
ax2 = sns.lineplot(x=np.arange(0, len(val_mean_abs_loss_df)), y=val_mean_abs_loss_df, label='Validation Loss', color='green')

plt.xlabel('Epoch')
plt.ylabel('Mean Absolute Error(LPM)')

#plt.ylim(0, 1000)

for axis in [ax1, ax2]:
    axis.yaxis.set_major_locator(MultipleLocator(100))

#plt.ylim(100, 1000)

plt.yscale('log')

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

ax1 = sns.lineplot(x=np.arange(0, len(mean_abs_per_loss_df)), y=mean_abs_per_loss_df, label='Train Loss', color='red')
ax2 = sns.lineplot(x=np.arange(0, len(val_mean_abs_per_loss_df)), y=val_mean_abs_per_loss_df, label='Validation Loss', color='green')

plt.xlabel('Epoch')

plt.yscale('log')
#plt.ylim(10, 100)
plt.ylabel('Relative Error(%)')

In [ ]:
fig, ax1 = plt.subplots()

sns.lineplot(x=val_loss_df, y=val_mean_abs_loss_df, ax=ax1, color='red')

ax1.set_xscale('log')
#ax1.set_xlim(10000, 2000000)
ax1.set_xlabel('Loss')

#ax1.set_yscale('log')
#ax1.set_ylim(0, 1000)
#ax1.yaxis.set_major_locator(MultipleLocator(2000))
ax1.set_ylabel('Absolute Error(LPM)')

ax2 = ax1.twinx()

sns.lineplot(x=val_loss_df, y=val_mean_abs_per_loss_df, ax=ax2, color='green')

ax2.set_yscale('log')
#ax2.set_ylim(500, 20000)
ax2.set_ylabel('Relative Error(%)')


line1, = ax1.lines
line2, = ax2.lines

ax1.legend([line1, line2], ['Absolute Error', 'Relative Error'], loc='upper left')

In [ ]:
model = keras.models.load_model('models/model.keras', custom_objects={'smape': smape})

In [ ]:
feature_name_list = ['pressure_1(bar)', 'main_pressure(bar)']
target_name = 'outlet_flowrate(lpm)'

file_name_list = os.listdir(os.path.join('data', 'ver_2'))
file_path_list = []

for file_name in file_name_list:
    file_path_list.append(os.path.join('data', 'ver_2', file_name))

dataset = load_dataset_v2(file_path_list)
dataset = dataset[::10]
dataset.reset_index(drop=True, inplace=True)

new_dataset = dataset.copy()
new_dataset = new_dataset[new_dataset[target_name] > 1]

train_bool_list = new_dataset['test_case_iter']!=3
train_data = new_dataset[train_bool_list]
train_data.reset_index(drop=True, inplace=True)

val_bool_list = new_dataset['test_case_iter']==3
val_data = new_dataset[val_bool_list]
val_data.reset_index(drop=True, inplace=True)

train_feature = train_data[feature_name_list].to_numpy()
val_feature = val_data[feature_name_list].to_numpy()

train_target = train_data[target_name].to_numpy()
val_target = val_data[target_name].to_numpy()

train_target = train_target.reshape(-1, 1)
val_target = val_target.reshape(-1, 1)

scaler = StandardScaler()
scaler.fit(train_target)

train_target = scaler.transform(train_target)
val_target = scaler.transform(val_target)

print(train_feature.shape, train_target.shape)

In [ ]:
seq_len = 30

train_feature, train_target = create_lstm_dataset(np.concatenate([train_feature, train_target], axis=1), seq_len=seq_len, pred_distance=0, target_idx_pos=train_feature.shape[1])
val_feature, val_target = create_lstm_dataset(np.concatenate([val_feature, val_target], axis=1), seq_len=seq_len, pred_distance=0, target_idx_pos=val_feature.shape[1])

train_target = np.squeeze(train_target)
val_target = np.squeeze(val_target)

print(train_feature.shape, train_target.shape)
print(val_feature.shape, val_target.shape)

In [ ]:
train_pred_raw = model.predict(train_feature, verbose=2)
val_pred_raw = model.predict(val_feature, verbose=2)

In [ ]:
train_target = scaler.inverse_transform(train_target.reshape(-1, 1))
train_target = np.squeeze(train_target)

val_target = scaler.inverse_transform(val_target.reshape(-1, 1))
val_target = np.squeeze(val_target)

In [ ]:
train_pred = scaler.inverse_transform(train_pred_raw)
val_pred = scaler.inverse_transform(val_pred_raw)

train_pred = np.squeeze(train_pred)
val_pred = np.squeeze(val_pred)

In [ ]:
print(r2_score(train_target, train_pred), r2_score(val_target, val_pred))
print(mean_absolute_error(train_target, train_pred), mean_absolute_error(val_target, val_pred))
print(mean_absolute_percentage_error(train_target, train_pred), mean_absolute_percentage_error(val_target, val_pred))

In [ ]:
pd.DataFrame(train_pred, columns=['train_pred']).to_csv(os.path.join('result','train_pred.csv'), index=False)
pd.DataFrame(val_pred, columns=['val_pred']).to_csv(os.path.join('result', 'val_pred.csv'), index=False)

In [ ]:
abs_error_arr = np.abs(val_target-val_pred)
relative_error_arr = (np.abs(val_target-val_pred)/val_target)*100

In [ ]:
sns.lineplot(val_target, color='red', linewidth=3)
sns.lineplot(val_pred, color='green', linestyle='--')

#plt.xlim(10000, 20000)
#plt.xlim(3500, 7000)

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

axis = sns.scatterplot(x=val_target, y=val_pred, edgecolor='black', hue=relative_error_arr, hue_norm=mcolors.LogNorm(), palette='rocket')

plt.xlim(-100, 2500)
plt.xlabel('Ground Truth Flow-rate(LPM)')

plt.ylim(-100, 2500)
plt.ylabel('Predicted Flow-rate(LPM)')

plt.legend(title='Relative Error(%)', ncol=2)

legend = axis.get_legend()
labels = legend.get_texts()

for text_obj in labels:
    text = text_obj.get_text()
    corrected_string = text.replace('−', '-')
    numeric_value = float(corrected_string)
    text_obj.set_text(f'{numeric_value:0.2f}')